name: firemate
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  intl: ^0.19.0
  firebase_core: ^2.25.4
  firebase_database: ^10.4.5
  url_launcher: ^6.2.4
  awesome_notifications: ^0.9.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
