name: firemate
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  intl: ^0.19.0
  firebase_core: ^2.25.4
  firebase_database: ^10.4.5
  url_launcher: ^6.2.4
  awesome_notifications: ^0.9.2
  confirm_dialog: ^1.0.3
  flutter:
    sdk: flutter
  firebase_messaging: ^14.7.19
  http: ^1.2.0
  flutter_local_notifications: ^17.1.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  image_path: "assets/favicon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
